AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CCFName:
    Type: String
  CCFRoleArn:
    Type: String
  CCFBucketName:
    Type: String
  CCFZipFileName:
    Type: String
  AppTierSubnet:
    Type: String
  DBTierSubnet:
    Type: String
  SGCCF:
    Type: String
Resources:
  BastionCloudCodeFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: nodejs14.x
      Role: !Ref CCFRoleArn
      FunctionName: !Ref CCFName
      Handler: index.handler
      Description: Cloud Code Functions that execute custom tasks
      TracingConfig:
        Mode: Active
      Code:
        S3Bucket: !Ref CCFBucketName
        S3Key: !Ref CCFZipFileName
      VpcConfig:
        SecurityGroupIds:
          - !Ref SGCCF
        SubnetIds:
          - !Ref AppTierSubnet
          - !Ref DBTierSubnet
