# Production copy. Remove SGs, Roles and Log Groups before updating
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCID:
    Type: String
    Default: vpc-0506ed18846c90ba5
  AppTierSubnet:
    Type: String
    Default: subnet-00369caabdf4fa5a6
  DBTierSubnet:
    Type: String
    Default: subnet-00369caabdf4fa5a6
  EFSSecurityGroup:
    Type: String
  SGAppServer:
    Type: String
  SGDBServer:
    Type: String
  ALBListener:
    Type: String
  NewNameSpace:
    Type: String
    Default: bastion
  ListenerRulePriority:
    Type: Number
    Default: 2
Resources:
  BaaSECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: BaaSECSCluster
    DependsOn:
      - AppServerLG
  AppServerECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref BaaSECSCluster
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      TaskDefinition: !Ref AppServerTask
      LaunchType: FARGATE
      ServiceRegistries:
        - RegistryArn: !GetAtt 
            - AppServerServiceDiscoveryEntry
            - Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            -  !Ref AppTierSubnet
          SecurityGroups:
            - !Ref AppServerSecurityGroup
      LoadBalancers:
        - ContainerPort: 3001
          ContainerName: app-server
          TargetGroupArn:
            Ref: AppServerTargetGroup
    DependsOn:
      - AppServerTask
      - AppServerServiceDiscoveryEntry
      - BaaSECSCluster
      - AppServerSecurityGroup
      - DatabaseECSService
      - AppServerTargetGroup
  AppServerTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt 
        - AppServerTaskRole
        - Arn
      TaskRoleArn: !GetAtt 
        - AppServerTaskRole
        - Arn
      RequiresCompatibilities:
        - FARGATE
      Family: fargate-task-definition
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: app-server
          Essential: 'true'
          Image: 'public.ecr.aws/y7d9d7k6/app-server:0.5.0'
          PortMappings:
            - ContainerPort: 3001
              HostPort: 3001
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppServerLG
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
    DependsOn:
      - BaaSECSCluster
      - AppServerLG
      - AppServerTaskRole
  DatabaseECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref BaaSECSCluster
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      TaskDefinition: !Ref DatabaseTask
      LaunchType: FARGATE
      ServiceRegistries:
        - RegistryArn: !GetAtt 
            - DatabaseServiceDiscoveryEntry
            - Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref AppTierSubnet
          SecurityGroups:
            - !Ref DatabaseSecurityGroup
    DependsOn:
      - DatabaseServiceDiscoveryEntry
      - DatabaseTask
      - BaaSECSCluster
      - DatabaseSecurityGroup
  DatabaseTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt 
        - DatabaseTaskRole
        - Arn
      TaskRoleArn: !GetAtt 
        - DatabaseTaskRole
        - Arn
      RequiresCompatibilities:
        - FARGATE
      Family: fargate-task-definition
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: mongo
          Essential: true
          Image: 'public.ecr.aws/y7d9d7k6/mongo:5.0.6'
          PortMappings:
            - ContainerPort: 27017
              HostPort: 27017
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppServerLG
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          MountPoints:
            - ContainerPath: /data/db
              SourceVolume: mongo-efs-volume
      Volumes:
        - Name: mongo-efs-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref InstanceEFS
    DependsOn:
      - BaaSECSCluster
      - DatabaseTaskRole
      - InstanceEFS
      - MountTarget
  BaaSNameSpace:
    Type: 'AWS::ServiceDiscovery::PrivateDnsNamespace'
    Properties:
      Description: Service Discovery Namespace for BaaS Instance
      Vpc: !Ref VPCID
      Name: !Ref NewNameSpace
  AppServerServiceDiscoveryEntry:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: app-server
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: '10'
        NamespaceId: !Ref BaaSNameSpace
      HealthCheckCustomConfig:
        FailureThreshold: '1'
    DependsOn:
      - BaaSNameSpace
  DatabaseServiceDiscoveryEntry:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: db
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: '10'
        NamespaceId: !Ref BaaSNameSpace
      HealthCheckCustomConfig:
        FailureThreshold: '1'
    DependsOn:
      - BaaSNameSpace
  InstanceEFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
  MountTarget:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref InstanceEFS
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref AppTierSubnet
    DependsOn:
      - InstanceEFS
  AppServerTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref VPCID
      Name: AppServerTargetGroup
      HealthCheckEnabled: true
      Port: 3001
      Protocol: HTTP
      TargetType: ip
  AppServerALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /server/*
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AppServerTargetGroup
                Weight: 1
