AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCID:
    Type: String
    Default: vpc-0506ed18846c90ba5
  AppTierSubnet:
    Type: String
    Default: subnet-00369caabdf4fa5a6
  DBTierSubnet:
    Type: String
    Default: subnet-00369caabdf4fa5a6
  EFSSecurityGroup:
    Type: String
  SGAppServer:
    Type: String
  SGDBServer:
    Type: String
  ALBListener:
    Type: String
  StackName:
    Type: String
  StackBucketName:
    Type: String
  ListenerRulePriority:
    Type: Number 
    Default: 2
  TargetGroupName:
    Type: String 
    Default: AppServerTargetGroup
  AppServerLG:
    Type: String
  ClusterName:
    Type: String
    Default: BaaSECSCluster
  RoutingPath:
    Type: String
    Default: /server/*
  ApiKey:
    Type: String
    Default: 'xxxxxxxxxxxxxxxxxxxxx'
  DBHost:
    Type: String
Resources:
  BaaSECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: !Ref ClusterName
  AppServerECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref BaaSECSCluster
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      TaskDefinition: !Ref AppServerTask
      LaunchType: FARGATE
      ServiceRegistries:
        - RegistryArn: !GetAtt 
            - AppServerServiceDiscoveryEntry
            - Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            -  !Ref AppTierSubnet 
          SecurityGroups:
            - !Ref AppServerSecurityGroup
      LoadBalancers:
        - ContainerPort: 3001
          ContainerName: app-server 
          TargetGroupArn:
            Ref: AppServerTargetGroup
    DependsOn:
      - AppServerTask
      - AppServerServiceDiscoveryEntry
      - BaaSECSCluster
      - AppServerSecurityGroup
      - DatabaseECSService
      - AppServerTargetGroup
  AppServerTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt 
        - AppServerTaskRole
        - Arn
      TaskRoleArn: !GetAtt 
        - AppServerTaskRole
        - Arn
      RequiresCompatibilities:
        - FARGATE
      Family: fargate-task-definition
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: app-server
          Essential: 'true'
          Image: 'public.ecr.aws/y7d9d7k6/app-server:0.7.2'
          PortMappings:
            - ContainerPort: 3001
              HostPort: 3001
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppServerLG
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref StackName
          Environment:
            - Name: apiKey
              Value: !Ref ApiKey
            - Name: stackName
              Value: !Ref StackName
            - Name: DB_HOST
              Value: !Ref DBHost
    DependsOn:
      - BaaSECSCluster
      - AppServerTaskRole
  AppServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 30000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 30000
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCID
      GroupDescription: Test
  AppServerTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AppServerTaskRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  DatabaseECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref BaaSECSCluster
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      TaskDefinition: !Ref DatabaseTask
      LaunchType: FARGATE
      ServiceRegistries:
        - RegistryArn: !GetAtt 
            - DatabaseServiceDiscoveryEntry
            - Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref AppTierSubnet 
          SecurityGroups:
            - !Ref DatabaseSecurityGroup
    DependsOn:
      - DatabaseServiceDiscoveryEntry
      - DatabaseTask
      - BaaSECSCluster
      - DatabaseSecurityGroup
  DatabaseTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt 
        - DatabaseTaskRole
        - Arn
      TaskRoleArn: !GetAtt 
        - DatabaseTaskRole
        - Arn
      RequiresCompatibilities:
        - FARGATE
      Family: fargate-task-definition
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: db-server
          Essential: true
          Image: 'public.ecr.aws/y7d9d7k6/mongo:5.0.6'
          PortMappings:
            - ContainerPort: 27017
              HostPort: 27017
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppServerLG
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref StackName
          MountPoints:
            - ContainerPath: /data/db
              SourceVolume: mongo-efs-volume
          Environment:
            - Name: MONGO_INITDB_ROOT_PASSWORD
              Value: db_password
            - Name: MONGO_INITDB_ROOT_USERNAME
              Value: bastion
      Volumes:
        - Name: mongo-efs-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref InstanceEFS
    DependsOn:
      - BaaSECSCluster
      - DatabaseTaskRole
      - InstanceEFS
      - MountTarget
  DatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 30000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 30000
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCID
      GroupDescription: Test
  DatabaseTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: DatabaseTaskRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  BaaSNameSpace:
    Type: 'AWS::ServiceDiscovery::PrivateDnsNamespace'
    Properties:
      Description: Service Discovery Namespace for BaaS Instance
      Vpc: !Ref VPCID
      Name: !Ref StackName 
  AppServerServiceDiscoveryEntry:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: app-server
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: '10'
        NamespaceId: !Ref BaaSNameSpace
    DependsOn:
      - BaaSNameSpace
  DatabaseServiceDiscoveryEntry:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: db
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: '10'
        NamespaceId: !Ref BaaSNameSpace
    DependsOn:
      - BaaSNameSpace
  InstanceEFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
  MountTarget:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref InstanceEFS
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref AppTierSubnet 
    DependsOn:
      - InstanceEFS
  AppServerTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref VPCID
      Name: !Ref TargetGroupName
      HealthCheckEnabled: true
      Port: 3001
      Protocol: HTTP
      TargetType: ip
  AppServerALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - !Ref RoutingPath
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AppServerTargetGroup
                Weight: 1
  StackBucket:
    Type: 'AWS::S3::Bucket'
    Description: S3 Bucket for Cloud Code Function zip files and file storage
    Properties:
      BucketName: !Ref StackBucketName
      VersioningConfiguration:
        Status: Suspended
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
